wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.4
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711206415.0
    t:
      1:
      - 5
      - 53
      - 55
      - 87
      - 95
      - 105
      2:
      - 5
      - 53
      - 55
      - 86
      - 87
      - 92
      - 95
      - 105
      3:
      - 2
      - 23
      4: 3.11.8
      5: 0.16.4
      8:
      - 1
      - 5
      9:
        2: llama_index
      13: darwin-x86_64
